In [1]:
import pandas as pd
import numpy as np
from sklearn import *

In [2]:
df=pd.read_csv('weight-height.csv')

In [3]:
df.head(10)

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801
5   Male  67.253016  152.212156
6   Male  68.785081  183.927889
7   Male  68.348516  167.971111
8   Male  67.018950  175.929440
9   Male  63.456494  156.399676

In [4]:
df.shape

(8555, 3)

In [5]:
df.isnull().sum()

Gender    0
Height    0
Weight    0
dtype: int64

In [6]:
df.Gender=preprocessing.LabelEncoder().fit_transform(df.Gender)

In [7]:
df.Height=preprocessing.StandardScaler().fit_transform(df[['Height']])
df.Weight=preprocessing.StandardScaler().fit_transform(df[['Weight']])

In [8]:
df

Gender    Height    Weight
0          1  1.827233  2.380023
1          1  0.512039 -0.103684
2          1  1.895545  1.470197
3          1  1.277788  1.698073
4          1  0.797634  1.270738
...      ...       ...       ...
8550       0 -1.642587 -1.718593
8551       0 -0.879344 -1.114506
8552       0 -0.318306 -0.302417
8553       0  0.161000 -0.435501
8554       0 -1.528897 -1.072934

[8555 rows x 3 columns]

In [9]:
x=df.drop('Weight',axis=1)

In [10]:
x

Gender    Height
0          1  1.827233
1          1  0.512039
2          1  1.895545
3          1  1.277788
4          1  0.797634
...      ...       ...
8550       0 -1.642587
8551       0 -0.879344
8552       0 -0.318306
8553       0  0.161000
8554       0 -1.528897

[8555 rows x 2 columns]

In [11]:
y=df['Weight']

In [12]:
y

0       2.380023
1      -0.103684
2       1.470197
3       1.698073
4       1.270738
          ...   
8550   -1.718593
8551   -1.114506
8552   -0.302417
8553   -0.435501
8554   -1.072934
Name: Weight, Length: 8555, dtype: float64

In [13]:
xtrain,xtest,ytrain,ytest=model_selection.train_test_split(x,y,test_size=.30,random_state=1)

In [14]:
xtest

Gender    Height
7154       0 -0.452294
3258       1  1.042451
2188       1  0.481319
5609       0 -0.213520
3186       1  1.062397
...      ...       ...
8004       0 -2.037375
7644       0 -0.050996
8521       0  0.281919
957        1  0.576735
233        1  1.211607

[2567 rows x 2 columns]

In [15]:
ytest

7154   -0.150802
3258    0.589349
2188    0.581425
5609    0.037806
3186    1.087120
          ...   
8004   -1.710793
7644   -0.531410
8521   -0.380633
957     0.145977
233     0.928776
Name: Weight, Length: 2567, dtype: float64

In [16]:
regress=linear_model.LinearRegression()

In [17]:
regress.fit(xtrain,ytrain)

LinearRegression()

In [18]:
predict_res=regress.predict(xtest)
predict_res

array([-0.68043716,  0.99561187,  0.59304621, ..., -0.15370062,
        0.66149925,  1.11696722])

# linear Accuracy

In [19]:
metrics.r2_score(ytest,predict_res)

0.9059959607091161

# linear MSE

In [20]:
metrics.mean_squared_error(ytest,predict_res)

0.09708113053084727

# linear Prediction score

In [21]:
regress.score(xtest,ytest)

0.9059959607091161

# KNN Regressor

In [22]:
neigh = neighbors.KNeighborsRegressor()

In [23]:
neigh.fit(xtrain,ytrain)

KNeighborsRegressor()

In [24]:
predict_neig=neigh.predict(xtest)
predict_neig

array([-0.48238561,  0.99338323,  0.41827163, ..., -0.16760663,
        0.46881764,  1.09018559])

# KNN Accuracy

In [25]:
metrics.r2_score(ytest,predict_neig)

0.8838502073708883

# KNN MSE

In [26]:
metrics.mean_squared_error(ytest,predict_neig)

0.11995179424647479

# KNN predict score

In [27]:
neigh.score(xtest,ytest)

0.8838502073708883

# Tuning:KNN Regressor

In [28]:
n_neighbors=np.random.randint(5,100,50)
weights=['uniform','distance']


parameters={
    'n_neighbors': n_neighbors, 
    'weights': weights
}

In [29]:
knn_fit=neigh.fit(xtrain,ytrain)
tune_knn=model_selection.RandomizedSearchCV(knn_fit,parameters,cv=3)

In [30]:
tune_knn.fit(xtrain,ytrain)

RandomizedSearchCV(cv=3, estimator=KNeighborsRegressor(),
                   param_distributions={'n_neighbors': array([43, 57, 32, 73, 41, 84, 25, 80, 57, 25, 80, 83, 55, 74, 81, 44, 28,
       58, 25, 29, 72, 51, 73, 56, 81, 59, 72,  5, 30, 17, 29, 83, 74, 42,
       30, 40, 42, 10, 68, 30, 83, 85, 86, 84, 31, 55, 62, 76, 26, 99]),
                                        'weights': ['uniform', 'distance']})

In [31]:
new_fit=tune_knn.best_estimator_

In [32]:
new_fit.fit(xtrain,ytrain)

KNeighborsRegressor(n_neighbors=43)

In [33]:
predict_tun=new_fit.predict(xtest)

# tune Accuracy score

In [34]:
metrics.r2_score(ytest,predict_tun)

0.9037514757394804

# tune MSE score

In [35]:
metrics.mean_squared_error(ytest,predict_tun)

0.0993990855884748

# tune Prediction score

In [36]:
new_fit.score(xtest,ytest)

0.9037514757394804

# KNN Classifier

In [67]:
dff=pd.read_csv('weight-height.csv')

In [69]:
dff.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [70]:
dff.Gender=preprocessing.LabelEncoder().fit_transform(df.Gender)

In [88]:
x=dff.drop('Gender',axis=1)

In [89]:
y=dff['Gender']

In [90]:
xtrain,xtest,ytrain,ytest=model_selection.train_test_split(x,y,test_size=.30,random_state=1)

In [91]:
kne_class=neighbors.KNeighborsClassifier()

In [92]:
kne_class.fit(xtrain,ytrain)

KNeighborsClassifier()

In [105]:
pre_res=kne_class.predict(xtest)
pre_res

array([1, 1, 1, ..., 0, 1, 1], dtype=int64)

In [106]:
#tn,fp,fn,tp=metrics.confusion_matrix(ytest,pre_res).ravel()
#result_sc=metrics.confusion_matrix(ytest,pre_res)

# KNN accuracy

In [104]:
metrics.accuracy_score(ytest,pre_res)

0.9146864043630697

# KNN Confusion Matrix

In [108]:
metrics.confusion_matrix(ytest,pre_res)

array([[ 938,  117],
       [ 102, 1410]], dtype=int64)

# KNN ROC

In [107]:
metrics.roc_auc_score(ytest,pre_res)

0.9108196043030166

# KNN Classification Report

In [113]:
metrics.classification_report(ytest,pre_res)

'              precision    recall  f1-score   support\n\n           0       0.90      0.89      0.90      1055\n           1       0.92      0.93      0.93      1512\n\n    accuracy                           0.91      2567\n   macro avg       0.91      0.91      0.91      2567\nweighted avg       0.91      0.91      0.91      2567\n'

In [115]:
n_neighbors=np.random.randint(5,100,50)
weights=['uniform','distance']


parameters1={
    'n_neighbors': n_neighbors, 
    'weights': weights
}

In [122]:
knn_fit1=neigh.fit(xtrain1,ytrain1)
tune_knn1=model_selection.RandomizedSearchCV(knn_fit1,parameters1,cv=3)

In [123]:
tune_knn1.fit(xtrain1,ytrain1)

RandomizedSearchCV(cv=3, estimator=KNeighborsRegressor(),
                   param_distributions={'n_neighbors': array([73, 47, 20, 99, 26, 23, 36, 66,  8, 80, 42, 86, 45, 83,  8, 46, 20,
        5, 62, 66, 71, 21, 37, 82, 98, 66,  5, 45, 14, 75, 90, 67,  8, 78,
       35, 70, 93, 71, 75, 32, 58, 73, 59, 43, 98, 78, 24, 14, 61, 99]),
                                        'weights': ['uniform', 'distance']})

In [124]:
new_fit1=tune_knn1.best_estimator_

In [125]:
new_fit1.fit(xtrain1,ytrain1)

KNeighborsRegressor(n_neighbors=71)

In [126]:
predict_tun1=new_fit1.predict(xtest1)

# tun KNN Accuracy

In [138]:
metrics.r2_score(ytest1,predict_tun1)

0.7566914667663175

# tun KNN Confusion Matrix

In [140]:
metrics.confusion_matrix(ytest1,predict_tun1.round(),normalize='true')

array([[0.89952607, 0.10047393],
       [0.06547619, 0.93452381]])

# tun KNN ROI Matrix

In [141]:
metrics.roc_auc_score(ytest1,predict_tun1)

0.9754115574613206

# tun KNN Classification Report

In [144]:
metrics.classification_report(ytest1,predict_tun1.round())

'              precision    recall  f1-score   support\n\n           0       0.91      0.90      0.90      1055\n           1       0.93      0.93      0.93      1512\n\n    accuracy                           0.92      2567\n   macro avg       0.92      0.92      0.92      2567\nweighted avg       0.92      0.92      0.92      2567\n'